name: GitHub Profile

on:
  push:
      branches: [ main ]
      paths-ignore:
        - 'README.md'
  schedule:
    - cron: "0 0 * * *"
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    name: generate-github-profile-3d-contrib
    steps:
      - uses: actions/checkout@v2
      - uses: yoshi389111/github-profile-3d-contrib@0.6.0
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          USERNAME: ${{ github.repository_owner }}
      - name: Commit & Push
        run: |
          git config user.name Yonghyun-Yoon
          git config user.email dgnppr@gmail.com
          git add -A .
          git commit -m "Update profile"
          git push
